//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_TBK
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ws_tbk", ConfigurationName="WS_TBK.ws_tbkPortType")]
    public interface ws_tbkPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="ws_tbk#ws_tbk:GetVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_TBK.GetVersionResponse> GetVersionAsync(WS_TBK.GetVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ws_tbk#ws_tbk:Get", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_TBK.GetResponse> GetAsync(WS_TBK.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ws_tbk#ws_tbk:Post", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_TBK.PostResponse> PostAsync(WS_TBK.PostRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersion", Namespace="ws_tbk", Order=0)]
        public WS_TBK.GetVersionRequestBody Body;
        
        public GetVersionRequest()
        {
        }
        
        public GetVersionRequest(WS_TBK.GetVersionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetVersionRequestBody
    {
        
        public GetVersionRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionResponse", Namespace="ws_tbk", Order=0)]
        public WS_TBK.GetVersionResponseBody Body;
        
        public GetVersionResponse()
        {
        }
        
        public GetVersionResponse(WS_TBK.GetVersionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ws_tbk")]
    public partial class GetVersionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetVersionResponseBody()
        {
        }
        
        public GetVersionResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="ws_tbk", Order=0)]
        public WS_TBK.GetRequestBody Body;
        
        public GetRequest()
        {
        }
        
        public GetRequest(WS_TBK.GetRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ws_tbk")]
    public partial class GetRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string method;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string @params;
        
        public GetRequestBody()
        {
        }
        
        public GetRequestBody(string method, string @params)
        {
            this.method = method;
            this.@params = @params;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="ws_tbk", Order=0)]
        public WS_TBK.GetResponseBody Body;
        
        public GetResponse()
        {
        }
        
        public GetResponse(WS_TBK.GetResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ws_tbk")]
    public partial class GetResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetResponseBody()
        {
        }
        
        public GetResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Post", Namespace="ws_tbk", Order=0)]
        public WS_TBK.PostRequestBody Body;
        
        public PostRequest()
        {
        }
        
        public PostRequest(WS_TBK.PostRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ws_tbk")]
    public partial class PostRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string method;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string @params;
        
        public PostRequestBody()
        {
        }
        
        public PostRequestBody(string method, string @params)
        {
            this.method = method;
            this.@params = @params;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostResponse", Namespace="ws_tbk", Order=0)]
        public WS_TBK.PostResponseBody Body;
        
        public PostResponse()
        {
        }
        
        public PostResponse(WS_TBK.PostResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ws_tbk")]
    public partial class PostResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public PostResponseBody()
        {
        }
        
        public PostResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface ws_tbkPortTypeChannel : WS_TBK.ws_tbkPortType, System.ServiceModel.IClientChannel
    {
    }
    
    // [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class ws_tbkPortTypeClient : System.ServiceModel.ClientBase<WS_TBK.ws_tbkPortType>, WS_TBK.ws_tbkPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>

        private string userName => @"Админ";
        //private string userName => @"ws";
        private string userPassword => "159753";

        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ws_tbkPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(ws_tbkPortTypeClient.GetBindingForEndpoint(endpointConfiguration), ws_tbkPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();

            this.ChannelFactory.Credentials.UserName.UserName = this.userName;
            this.ChannelFactory.Credentials.UserName.Password = this.userPassword;

            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        public ws_tbkPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ws_tbkPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {

            this.Endpoint.Name = endpointConfiguration.ToString();

            this.ChannelFactory.Credentials.UserName.UserName = this.userName;
            this.ChannelFactory.Credentials.UserName.Password = this.userPassword;

            

            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ws_tbkPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress, System.ServiceModel.Description.ClientCredentials clientCredentials) : 
                base(ws_tbkPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();

            this.ChannelFactory.Credentials.UserName.UserName = this.userName;
            this.ChannelFactory.Credentials.UserName.Password = this.userPassword;

            ConfigureEndpoint(this.Endpoint, clientCredentials);
        }
        
        public ws_tbkPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ws_tbkPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();

            this.ChannelFactory.Credentials.UserName.UserName = this.userName;
            this.ChannelFactory.Credentials.UserName.Password = this.userPassword;

            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_tbkPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
            this.ChannelFactory.Credentials.UserName.UserName = this.userName;
            this.ChannelFactory.Credentials.UserName.Password = this.userPassword;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_TBK.GetVersionResponse> WS_TBK.ws_tbkPortType.GetVersionAsync(WS_TBK.GetVersionRequest request)
        {
            return base.Channel.GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_TBK.GetVersionResponse> GetVersionAsync()
        {
            WS_TBK.GetVersionRequest inValue = new WS_TBK.GetVersionRequest();
            inValue.Body = new WS_TBK.GetVersionRequestBody();
            return ((WS_TBK.ws_tbkPortType)(this)).GetVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_TBK.GetResponse> WS_TBK.ws_tbkPortType.GetAsync(WS_TBK.GetRequest request)
        {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_TBK.GetResponse> GetAsync(string method, string @params)
        {
            WS_TBK.GetRequest inValue = new WS_TBK.GetRequest();
            inValue.Body = new WS_TBK.GetRequestBody();
            inValue.Body.method = method;
            inValue.Body.@params = @params;
            return ((WS_TBK.ws_tbkPortType)(this)).GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_TBK.PostResponse> WS_TBK.ws_tbkPortType.PostAsync(WS_TBK.PostRequest request)
        {
            return base.Channel.PostAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_TBK.PostResponse> PostAsync(string method, string @params)
        {
            WS_TBK.PostRequest inValue = new WS_TBK.PostRequest();
            inValue.Body = new WS_TBK.PostRequestBody();
            inValue.Body.method = method;
            inValue.Body.@params = @params;
            return ((WS_TBK.ws_tbkPortType)(this)).PostAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ws_tbkSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                
                
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;               
                
                //result.TextEncoding = System.Text.Encoding.UTF8;
                result.TextEncoding = System.Text.Encoding.BigEndianUnicode;

                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ws_tbkSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();

                
                httpBindingElement.AuthenticationScheme = System.Net.AuthenticationSchemes.Basic;

                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ws_tbkSoap))
            {
                //return new System.ServiceModel.EndpointAddress($"{url}/ws/ws_tbk");
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/retail_1/ws/ws_tbk");
            }
            if ((endpointConfiguration == EndpointConfiguration.ws_tbkSoap12))
            {
                //return new System.ServiceModel.EndpointAddress($"{url}/ws/ws_tbk");
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/retail_1/ws/ws_tbk");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ws_tbkSoap,
            
            ws_tbkSoap12,
        }
    }
}
